### ISSUE TITLE
Update multiple connector configmaps

### ISSUE THREAD

**Issue by oun** [confluentinc/kafka-devops#34]
Hi,

I tried add,update,delete multiple connector configmaps in the same git commit but the connect-operator did not execute all configmaps that were changed. The operator only process the first event in the binding-context. I can create pull request to enhance the connect-operator.

Thanks

**Comment by rspurgeon** [comment]
@oun LMK if you'd like me to look at any issues you found w/ the connect-operator.  Thank you for evaluating the project

**Comment by oun** [comment]
I have multiple configmaps. For example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: source-connector
    files:
      - source-connector.json=source-connector.json
  - name: sink-connector
    files:
      - sink-connector.json=sink-connector.json
  - name: outbox-connector
    files:
      - outbox-connector.json=outbox-connector.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    destination: connect
```
When I update all connector config files and apply it to cluster, the connect operator did not update all the connectors. I found that the binding context contained multiple events but the hook::run function get only the first object in the binding context.

Thank you
